name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  linux-build:
    name: Linux Build
    strategy:
      matrix:
        cc: [ gcc, clang ]
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
        # Github is broken
      - name: Submodule Tags
        run: |
          cd lib/c-utils
          git fetch --tags 
      - name: build
        run: |
          make clean debug CC=${{ matrix.cc }}
          make clean release CC=${{ matrix.cc }}

  macos-build:
    name: MacOS Build
    strategy:
      matrix:
        cc: [ gcc-13, clang ]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Submodule Tags
        run: |
          cd lib/c-utils
          git fetch --tags 
      - name: build
        run: |
          make clean debug CC=${{ matrix.cc }}
          make clean release CC=${{ matrix.cc }}
