name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  linux-build:
    name: Linux Build
    strategy:
      matrix:
        cc: [ gcc, clang ]
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: clone library
        run: git clone https://github.com/vladaviedov/nanorl
      - name: build library
        run: |
          cd nanorl
          git submodule update --init
          make CC=${{ matrix.cc }} -j$(nproc)
          sudo make install
          sudo ldconfig
      - name: build binary
        run: make CC=${{ matrix.cc }}

  macos-build:
    name: MacOS Build
    strategy:
      matrix:
        cc: [ gcc-13, clang ]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: clone library
        run: git clone https://github.com/vladaviedov/nanorl
      - name: build library
        run: |
          cd nanorl
          git submodule update --init
          make CC=${{ matrix.cc }} -j$(nproc)
          sudo make install PREFIX=/usr/local
      - name: build binary
        run: |
          export LIBRARY_PATH=/usr/local/lib
          export CPATH=/usr/local/include
          make CC=${{ matrix.cc }}
